image: thlmylab/swakkd:stable

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  NAMESPACE: stud-eedert-ba

stages: 
  - prepare 
  - build 
  - deploy

gitlab-registry:
  stage: prepare
  image: 'thlmylab/swakkd:stable'  
  script:
    - kubectl delete secret gitlab-registry-secret -n $NAMESPACE || true
    - |
      kubectl create secret docker-registry gitlab-registry-secret \
      --docker-server=$CI_REGISTRY \
      --docker-username=image-registry \
      --docker-password=$CI_REGISTRY_TOKEN -n $NAMESPACE

build:
  stage: build
  services: ["docker:dind"]
  rules:
    - if: $CI_COMMIT_REF_SLUG == "master"
      changes:
        - ./Dockerfile
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

learnapp-deployment:
  stage: deploy
  script: 
    - cd deploy
    - kubectl apply -f deployment.yaml -n $NAMESPACE
    - kubectl apply -f service.yaml -n $NAMESPACE
  rules:
    - if: $CI_COMMIT_REF_SLUG == "master"
      changes:
        - deploy/*

mysql-deployment: 
  stage: deploy
  script: 
    - cd deploy 
    - kubectl create secret generic learningapp-mysql-secret --from-literal=mysql-root-password=$MYSQL_ROOT_PASSWORD --namespace=$NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    - kubectl apply -f mysql.yaml -n $NAMESPACE
  rules:
    - if: $CI_COMMIT_REF_SLUG == "master"
      changes:
        - deploy/mysql.yaml
