services:
    adminer:
        image: adminer
        ports:
            - 8080:8080
    mysql:
        image: mysql
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
    circuloapp:
        image: elisabethedert1998/circulo:latest
        env_file:
            - .env
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        ports:
            - 80:8080
volumes:
    mysql_data:
        driver: local