apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningapp-deployment
  labels:
    app: learningapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningapp
  template:
    metadata:
      labels:
        app: learningapp
    spec:
      containers:
      - name: learningapp-pod
        image: git.mylab.th-luebeck.de:4181/elisabeth.edert/eedert_abschlussarbeit_prototyp:master
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
      imagePullSecrets:
      - name: gitlab-registry-secret
