apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningapp-phpmyadmin
  namespace: stud-eedert-ba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningapp-phpmyadmin
  template:
    metadata:
      labels:
        app: learningapp-phpmyadmin
    spec:
      containers:
      - name: learningapp-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "mysql" # Name des MySQL-Services
        - name: PMA_PORT
          value: "3306"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: learningapp-phpmyadmin
  namespace: stud-eedert-ba
spec:
  selector:
    app: learningapp-phpmyadmin
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
